[박정현] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-4-team pull request #13
Opened 2021-11-19 08:24 UTC by haileyjpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
- 브랜치 네임 수정 (from junhyun-models to junghyun-signup)
		 
## 수정 사항들 자세한 내용
- 필요없는 import들 삭제
- 브랜치 네임 수정  (from junhyun-models to junghyun-signup)

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-19 09:55 UTC, bigfanoftim requested changes

2021-11-19 09:55 UTC, bigfanoftim commented on students/junghyun/users/models.py
>  	updated_at = models.DateTimeField(auto_now=True)
코드내에 클래스 단위로, 혹은 함수 단위로 `=` 을 기준으로 하여 코드 정렬해주세요!

```python
# BAD
point = models.DecimalField(max_digits=2, decimal_places=1)
user = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)

# GOOD
point      = models.DecimalField(max_digits=2, decimal_places=1)
user       = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie      = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)
```

2021-11-19 09:55 UTC, bigfanoftim commented on students/junghyun/users/views.py
> +class UsersView(View):
작성해주신 `class`는 `회원가입을 위한 View`이기 때문에 그에 맞게 네이밍을 해주세요!
```suggestion
class SignUpView(View):
```

2021-11-19 09:55 UTC, bigfanoftim commented on students/junghyun/users/views.py
> +from .models import User
불필요한 `import`문은 지워주시고, `import`문 순서를 잘 지켜서 만들어주세요.
```suggestion
import re, json

from django.http  import JsonResponse
from django.views import View

from .models import User
```

2021-11-19 09:55 UTC, bigfanoftim commented on students/junghyun/users/urls.py
> +]
이 부분도 아래 `View Class`의 이름을 수정하면서 같이 수정해주시면 되겠습니다!
그리고 라운지에서 말씀드린 내용대로 회원가입 기능에 해당하는 `SignUpView`를 맵핑해주는 경우, 그에 맞게 주소도 작성해주세요!
```suggestion
from users.views  import SignUpView

urlpatterns = [
    path('/signup', SignUpView.as_view()),
]
```

2021-11-19 09:55 UTC, bigfanoftim commented on students/junghyun/users/views.py
> +            password_validation = "^.*(?=^.{8,}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%*^&+=]).*$"
위와 같이 코드내에 클래스 단위로, 혹은 함수 단위로 = 을 기준으로 하여 코드 정렬해주세요!

2021-11-19 09:55 UTC, bigfanoftim commented on students/junghyun/westagram/settings.py
> +    'users',
불필요한 들여쓰기가 되어있네요!
```suggestion
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
```

2021-11-19 12:08 UTC, haileyjpark commented on students/junghyun/users/urls.py
> +]
수정사항이 하나도 반영이 안된 상태로 푸쉬가 되었네요 ㅠㅠ 다시 했습니다!

2021-11-21 15:46 UTC, kyeongraekim requested changes
아래 내용 참고하여 수정해주세요!~

2021-11-21 15:46 UTC, kyeongraekim commented on students/junghyun/users/models.py
> +	phonenumber = models.CharField(max_length=20)
snake case로 중간의 띄어쓰기를 표현해주세요!~

2021-11-21 15:46 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +from django.core.exceptions import ValidationError, ObjectDoesNotExist
아직 사용하지 않은 ObjectDoesNotExist 에러 메세지도 임포트해주시고 계시네요!~ 로그인시 사용 하실 것으로 보이는데 추후에 컨플릭트가 날 가능성이 있고 현재 브랜치선에서는 사용되지 않으니 삭제해 주세요~

2021-11-21 15:46 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +            return JsonResponse({"message":e.message}, status=401)
클라이언트에게 리턴하는 에러 메세지는 장고에서 건내주는 에러메세지를 바로 보내는 것 보다 커스터마이징된 메세지를 보내는 것을 권장드립니다!~ 해당 내용은 스스로 디버깅할 때 더 좋은 에러 메세지일 것으로 보입니다!~

2021-11-22 02:17 UTC, kyeongraekim requested changes
아래 내용 확인해주셔서 수정 반영해주세요!~

2021-11-22 02:17 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +                information  = data["info"],
information은 현재 db 기획상 null 값을 허용해주고 계시네요!~ 파이썬 딕셔너리 매핑의 또다른 메소드인 .get()을 사용하셔서 null 값을 다룰 수 있게 코드를 변경해보세요!~

2021-11-22 02:17 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +                raise ValidationError("INVALID_ERROR")
- 이메일과 패스워드 유효성 검사 조건절을 둘로 나누어 주세요!~
- 그리고 에러메세지도 Invalid_Error 는 디버깅 시 너무 모호한 메세지로 보여질 것 같습니다. Invalid_Email, Invalid_password, user_already_exists 등 보다 정확한 에러메세지를 리턴해주세요!~

2021-11-22 07:27 UTC, kyeongraekim commented
LGTM!~

2021-11-22 07:27 UTC, merged