[성종호] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-4-team pull request #15
Opened 2021-11-19 16:02 UTC by SeongJongHo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-21 15:34 UTC, kyeongraekim requested changes
안녕하세요 종호님 아래 내용 확인해서 수정해주세요!~

2021-11-21 15:34 UTC, kyeongraekim commented on students/jongho/users/models.py
>      updated_at =models.DateTimeField(auto_now=True)
변수명 컨벤션은 가장 긴 변수명 기준으로 스페이스 한칸 띄어주세요~ information 이후 공백이 필요해 보이네요!~

2021-11-21 15:34 UTC, kyeongraekim commented on students/jongho/users/views.py
> +import re
제일 최상단으로 위치를 옮겨서 json, re 로 넣어 주시면 더 컨벤션상 깔끔해 보일 것 같네요!~

2021-11-21 15:34 UTC, kyeongraekim commented on students/jongho/users/views.py
> +      password_confirm = re.compile('^.*(?=^.{8,15}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$')
정규표현식을 이용한 validation 검증임을 드러낼 수 있게 변수명에 regex라는 용어가 들어가면 좋을 것 같아 보여요!~

2021-11-21 15:34 UTC, kyeongraekim commented on students/jongho/users/views.py
> +        return JsonResponse({'message':"Id,Pw 확인"},status=400)
모든 리턴 메세지는  http 통신상 발생 될 수 있는 변수를 최소화할 수 있게 최대한 영문으로 작성해주세요!~

2021-11-21 15:34 UTC, kyeongraekim commented on students/jongho/users/views.py
> +    except KeyError:
키에러말고 발생할 수 있는 다른 에러들은 없을까요? 조금만 더 고민해서 반영해주세요!~

2021-11-21 15:34 UTC, kyeongraekim commented on students/jongho/users/views.py
> +          information = data['information']
information은 model 상  blank=True 또는 null=True을 반영하여서, 회원가입 이후의 선택적 기입사항으로 기획해주셨다면 실제 인스타그램의 기획과 부합하는 코드가 되었을 것 같네요!~ 필수입력사항과 선택입력사항에 대한 고민을 내가 실제 개발자라면 어떻게 했을까? 라는 자문과 함께 끊임없이 고민해주세요!~

2021-11-22 07:22 UTC, bigfanoftim requested changes

2021-11-22 07:22 UTC, bigfanoftim commented on students/jongho/users/models.py
> +    phone       = models.CharField(max_length=200)
`phone`이라고 변수명을 지정해주시면 휴대폰 기종인지, 휴대폰 통신사인지, 휴대폰 번호인지 알 수 없습니다. 정확한 변수명으로 작성해주세요!
```suggestion
```

2021-11-22 07:22 UTC, bigfanoftim commented on students/jongho/users/models.py
> +    id          = models.AutoField(primary_key=True)
모델링 시 `Primary Key`는 따로 지정해주지 않아도 자동으로 생성됩니다!
```suggestion
```

2021-11-22 07:22 UTC, bigfanoftim commented on students/jongho/users/models.py
> +    email       = models.EmailField(unique=True)
`email`도 `max_length`속성이 있으면 좋을 것 같습니다!

2021-11-22 07:22 UTC, bigfanoftim commented on students/jongho/users/models.py
>        db_table="users"
코드는 항상 가독성을 생각하고 작성해주세요!
```suggestion
      db_table = "users"
```

2021-11-22 07:22 UTC, bigfanoftim commented on students/jongho/users/views.py
> +
불필요한 띄어쓰기 제거해주세요!
```suggestion
```

2021-11-23 01:43 UTC, bigfanoftim requested changes

2021-11-23 01:43 UTC, bigfanoftim commented on students/jongho/users/views.py
> +class SignUp(View):
View 이름은 컨벤션에 맞게 항상 아래와 같이 작성해주세요! 그에 맞게 urls.py도 수정해주세요!
```suggestion
class SignUpView(View):
```

2021-11-23 01:43 UTC, bigfanoftim commented on students/jongho/users/views.py
> +        return JsonResponse({'message':"INVALID_EGTIKEUL"},status=400)
작성해주신 if문은 이미 존재하는 이메일인지 확인하는 로직입니다. 그에 맞는 에러 메세지로 작성해주세요.
```suggestion
      if User.objects.filter(email=data["email"]).exists():
        return JsonResponse({'message':"email_already_exists"},status=400)
```

2021-11-23 05:58 UTC, merged