[박정현] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-4-team pull request #18
Opened 2021-11-22 08:45 UTC by haileyjpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Validation Module 어떻게 만들고 import해오나요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 12:17 UTC, SeongJongHo commented on students/junghyun/users/views.py
> +from django.core.exceptions import ValidationError, ObjectDoesNotExist
ValidationError와ObjectDoesNotExist 부분 공백없어도 될것 같습니다!

2021-11-22 12:17 UTC, SeongJongHo commented on students/junghyun/users/views.py
>  from .models                import User
여기도 공백 2줄있는데 1줄이여야 될것같아요!

2021-11-22 12:17 UTC, SeongJongHo commented on students/junghyun/users/views.py
> +    def signuppost(request):
저도 안해봐서 모르겠는데 post를 signuppost로 바꿔도 작동하는지 궁금합니다!

2021-11-22 12:17 UTC, SeongJongHo commented on students/junghyun/users/views.py
> +            if (password != data['password']):
()소괄호가 묶어주는데 사용하는걸로 알고있는데 이경우에 꼭 써야하는지 궁금합니다

2021-11-22 12:57 UTC, haileyjpark commented on students/junghyun/users/views.py
> +from django.core.exceptions import ValidationError, ObjectDoesNotExist
> ValidationError와ObjectDoesNotExist 부분 공백없어도 될것 같습니다!

다른 분들이 공백 있는 것이 더 좋을 것 같다고 해서 그냥 뒀는데 컨벤션이라고 하면 수정하겠습니다!!!감사합니다!!

2021-11-22 12:57 UTC, haileyjpark commented on students/junghyun/users/views.py
>  from .models                import User
감사합니다!

> 여기도 공백 2줄있는데 1줄이여야 될것같아요!

2021-11-22 12:58 UTC, haileyjpark commented on students/junghyun/users/views.py
> +    def signuppost(request):
실수입니다! 수정했습니다!

> 저도 안해봐서 모르겠는데 post를 signuppost로 바꿔도 작동하는지 궁금합니다!

2021-11-22 12:58 UTC, MinhyukK0 commented on students/junghyun/users/views.py
import하는 요소를 합칠수 있지 않을까요?

2021-11-22 12:59 UTC, haileyjpark commented on students/junghyun/users/views.py
> +            if (password != data['password']):
컴퓨터가 다른 부호들이랑 :랑 헷갈려할까봐 넣었습니당!

> ()소괄호가 묶어주는데 사용하는걸로 알고있는데 이경우에 꼭 써야하는지 궁금합니다

2021-11-22 13:11 UTC, Djangowon commented on students/junghyun/users/validator.py
> +        raise ValidationError("INVALID_PASSWORD")
LGTM~!  🔥

2021-11-22 14:40 UTC, dk-sync commented on students/junghyun/users/views.py
> +            return JsonResponse({'message':e.message}, status = 401)
경래님께서 전체 에러메세지를 반환하는 것은 보안성의 취약점으로 직결되기에 지양 해달라고 하셔가지고 한번 확인해보시는 것도 괜찮을 것 같아요!

2021-11-22 15:38 UTC, haileyjpark commented on students/junghyun/users/views.py
> +            return JsonResponse({'message':e.message}, status = 401)
> 경래님께서 전체 에러메세지를 반환하는 것은 보안성의 취약점으로 직결되기에 지양 해달라고 하셔가지고 한번 확인해보시는 것도 괜찮을 것 같아요!

감사합니다! 저 e메세지로 해서 각각 다른 메세지로 나오게 validation.py에 따로 뺐어요!

2021-11-23 01:41 UTC, kyeongraekim requested changes
정현님 안녕하세요~ 아래 내용 확인해서 수정해주세요!

2021-11-23 01:41 UTC, kyeongraekim commented on students/junghyun/users/validator.py
> +password_regex = "^.*(?=^.{8,}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%*^&+=]).*$"
문자열로만 이루어진 정규표현식,  숫자로만 이루어진 상수 데이터는 파이썬 컨벤션상 모두 대문자로 작성해줍니다~ 참고 바랍니다!

2021-11-23 01:41 UTC, kyeongraekim commented on students/junghyun/users/validator.py
> +def pw_validation(password):
함수명에 영어 약어보다 원어를 전체 풀어쓰는 것을 권장드립니다!~ 개발자들에게 있어 변수,함수,클래스명 네이밍은 정말 고심과 고심끝에 이루어져야하는 작업임을 당부드립니다~

2021-11-23 01:41 UTC, kyeongraekim commented on students/junghyun/users/validator.py
> +def regex_match(regex, value):
정규표현식 함수는 이메일용, 패스워드용으로 따로따로 구분해주심을 추천드립니다!~ 하나의 함수는 하나의 기능을 가져야만 하며 가장 기초 단위에 대한 작업이라고 할 수 있겠습니다. 지금부터 이러한 방향으로 코드를 짜주시면서 향후 코드의 확장성을 고려한 코딩을 지향해주세요~

2021-11-23 01:41 UTC, kyeongraekim commented on students/junghyun/users/validator.py
> +def pw_validation(password):
추가로 validation.py 에 들어가야 하는 코드 내용은 의미와 기능상 정규표현식만을 추가 해주시면 될 것 같아 보입니다!~
email_exists 나 pw_validation은 따로 모듈화 하실 필요 없이 view 코드 내에서 로직으로 처리해주세요!~

2021-11-23 01:41 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +        except ObjectDoesNotExist:
장고 에러상 ObjectDoesNotExist와 Model.DoesNotExist의 차이점을 살펴보고 더 나은 것을 골라서 적용해주세요!~

2021-11-23 04:18 UTC, haileyjpark commented on students/junghyun/users/validator.py
> +def pw_validation(password):
감사합니다 수정했습니다~!~!~!

2021-11-23 04:18 UTC, haileyjpark commented on students/junghyun/users/validator.py
> +password_regex = "^.*(?=^.{8,}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%*^&+=]).*$"
이 부분 구두로 여쭤볼게요~!~

2021-11-23 04:18 UTC, haileyjpark commented on students/junghyun/users/validator.py
> +def regex_match(regex, value):
감사합니다 수정했습니다~!~!!!!

2021-11-23 04:19 UTC, haileyjpark commented on students/junghyun/users/views.py
> +        except ObjectDoesNotExist:
네 차이점 살펴보고 수정햇씁니다 감사합니다!!!!

2021-11-23 07:48 UTC, bigfanoftim requested changes

2021-11-23 07:48 UTC, bigfanoftim commented on students/junghyun/users/views.py
> +            return JsonResponse({'message':'INVALID_EMAIL'}, status=401)
이 에러는 정현님 로직상 이메일만 판단해서 나오는 에러가 아닙니다! 에러 메세지를 조금 더 명확하게 적어주세요!
```suggestion
        except User.DoesNotExist:
            return JsonResponse({'message':'invalid_user'}, status=401)
```

2021-11-23 07:48 UTC, bigfanoftim commented on students/junghyun/users/views.py
> +from .validator             import *
`import` 하실 때 `*`로 모든 것을 다 불러오게 된다면, 나중에 `validator`에서 다른 코드가 추가되었을때 불필요하게 다 가져오게 됩니다. 항상 필요한 것만 `import` 해주세요!

2021-11-23 07:53 UTC, haileyjpark commented on students/junghyun/users/views.py
> +from .validator             import *
네 감사합니다 수정했습니다~!~!~!~!

2021-11-23 07:54 UTC, haileyjpark commented on students/junghyun/users/views.py
> +            return JsonResponse({'message':'INVALID_EMAIL'}, status=401)
네 감사합니다 수정했습니다~!~!~!

2021-11-23 07:54 UTC, merged