[성종호] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-4-team pull request #20
Opened 2021-11-23 06:47 UTC by SeongJongHo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 07:03 UTC, jaemoon406 commented
LGTM~!

2021-11-23 07:03 UTC, jaemoon406 commented
LGTM~!

2021-11-23 07:58 UTC, haileyjpark commented on students/jongho/users/my_module.py
> +    raise ValidationError("INVALID_PASSWORD")
module 이름은 my_module로 하신 이유가 있나용? 혹시 나중에 module이 많아지면 헷갈릴 수 있지 않을까용?

2021-11-23 07:58 UTC, haileyjpark commented on students/jongho/users/views.py
> +      information  = data.get("information","")
get 함수에 default값을 빈 문자열로 주신 이유가 있나요?

2021-11-23 07:58 UTC, haileyjpark commented on students/jongho/users/views.py
> +      email_regex(data) #DB hit전에 정규표현식 검사
Signin 과정에 정규표현식 검사를 넣으신 이유가 있을까용?

2021-11-23 07:58 UTC, haileyjpark commented on students/jongho/users/views.py
> +
에러 반환을 한 줄로 줄일 수 있는 방법도 있을 것 같아요~!~!~!~!~!

2021-11-23 08:15 UTC, SeongJongHo commented on students/jongho/users/views.py
> +
수정하겠습니다.!

2021-11-23 08:15 UTC, SeongJongHo commented on students/jongho/users/views.py
> +      email_regex(data) #DB hit전에 정규표현식 검사
프론트단에서 정규표현식 검사를 안한다는 가정하에 로그인시 email을 입력해야 하는 상황에서 Id만 입력하는등의 상황을 고려하여서
넣어봤습니다. db hit를 한번하냐 두번하냐의 차이로 filter와 get사용을 선택하기도 해서 db hit횟수를 줄이는게 좋다고 판단하여 그렇게 했습니다.!

2021-11-23 08:15 UTC, SeongJongHo commented on students/jongho/users/views.py
> +      information  = data.get("information","")
blank 와 null중에 blank가 Django 컨벤션이기도 하고 Django에서 권유하고 있기에 default값으로 빈문자열을주었습니다.

2021-11-23 08:16 UTC, SeongJongHo commented on students/jongho/users/my_module.py
> +    raise ValidationError("INVALID_PASSWORD")
수정하겠습니다!

2021-11-23 16:12 UTC, kyeongraekim requested changes

2021-11-23 16:12 UTC, kyeongraekim commented on students/jongho/users/views.py
> +from .validation   import email_regex,password_regex
컨벤션 신경써주세요!~

2021-11-23 16:12 UTC, kyeongraekim commented on students/jongho/users/views.py
> +      email_regex(data)
의미 기능상 다른 내용이 시작됨으로 줄바꿈 공백 한칸이 필요시 되보이네요

2021-11-23 16:12 UTC, kyeongraekim commented on students/jongho/users/views.py
> +      email_regex(data) #DB hit전에 정규표현식 검사
정규표현식은 회원가입시에 만 넣어주셔도 무방해보입니다!~ 요즘 대부분의 웹서비스는 프론트단에서 올바른 입력이 되지 않으면 버튼이 활성화 되지 않게 기획되고 있습니다~

2021-11-24 00:50 UTC, SeongJongHo commented on students/jongho/users/views.py
> +from .validation   import email_regex,password_regex
수정했습니다!

2021-11-24 00:50 UTC, SeongJongHo commented on students/jongho/users/views.py
> +      email_regex(data)
수정했습니다!

2021-11-24 01:19 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-24 01:19 UTC, merged