[김순태] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/27-westagram-backend-4-team pull request #23
Opened 2021-11-23 08:33 UTC by haileyjpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 비밀번호 bcrypt 적용하여 암호화 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- bcrypt import시 밑줄이 뜨는데 기능은 잘 작동이 되는 이유가 궁금합니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 08:49 UTC, SeongJongHo commented
LGTM!~!~!~!

2021-11-23 08:50 UTC, SeongJongHo commented
LGTM!~

2021-11-23 10:40 UTC, MinhyukK0 commented on students/junghyun/users/views.py
> +            return JsonResponse({'message':'INVALID_EMAIL'},status = 401)
LGTM~

2021-11-23 11:38 UTC, jaemoon406 commented
LGTM~!!!

2021-11-23 16:09 UTC, kyeongraekim requested changes
아래 내용 확인하여서 수정에 반영해주세요!

2021-11-23 16:09 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +                password      = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode(),
보다 나은 가독성을 위해 create 직전에 hashed_password 라는 변수명을 선언해서 해당 내용을 넣어주세요!~

2021-11-23 16:09 UTC, kyeongraekim commented on students/junghyun/users/views.py
>                  phone_number  = data["phone_number"],
phonenumber와 name 의 키매핑도 위 try문 바로 직후에 넣어주시면 만일 키에러가 났을 경우 불필요하게 validation 모듈이나 바로 아래 if문을 훑을 일이 없겠죠? 한 번 곰곰히 생각해보세요!~

2021-11-23 16:09 UTC, kyeongraekim commented on students/junghyun/users/views.py
> +            return JsonResponse({'message':'INVALID_EMAIL'},status = 401)
해당 내용은 6번 과제 올릴 떄 올려주셔야 함으로 추후에 푸시해주세요!~ 기능에 맞는 푸시를 위해서, 깃을 보다 깃답게 쓰기 위해 조금 엄격히 관리 중이니 이점 양해 부탁드립니다!~

2021-11-24 00:05 UTC, haileyjpark commented on students/junghyun/users/views.py
> +                password      = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode(),
네 수정했습니다 감사합니다~!~!

2021-11-24 01:59 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-11-24 01:59 UTC, merged