[이재문] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-4-team pull request #24
Opened 2021-11-23 08:55 UTC by jaemoon406

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 08:59 UTC, haileyjpark commented on students/jaemoon/users/views.py
> +                return JsonResponse({'message':'SUCCESS'},status=200)
user = User.objects.get(email=data['email'])

            if not user:
                return JsonResponse({'message': 'INVALID_USER'}, status=400)
            if user.password == data['password']:
                return JsonResponse({'message':'SUCCESS'},status=200)



이 과정을 두 줄로 줄일 수 있지 않을까요?

2021-11-23 09:06 UTC, SeongJongHo commented on students/jaemoon/users/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=400)
not user 조건문 들어가기전에 get으로 해당 유저가 없을경우 error를 일으켜서 if not user 부분은 없어도 될것같습니다
except로 error를 잡아주시면 좋을것같아요

2021-11-23 09:06 UTC, SeongJongHo commented on students/jaemoon/users/views.py
> +
로그인이 안됬을경우 success말고 다른 error메세지를 넣어주셔야 할것 같아요

2021-11-23 16:06 UTC, kyeongraekim requested changes

2021-11-23 16:06 UTC, kyeongraekim commented on students/jaemoon/users/views.py
> +            return JsonResponse({'message':'PASSWORD_ERROR'},status=401)
리턴되는 메세지가 패스워드 에러만 잡고 있네요? 논리 흐름상 맞는 내용인지 재확인 부탁드립니다!~

2021-11-24 08:20 UTC, kyeongraekim approved these changes

2021-11-24 08:21 UTC, merged

2021-11-24 08:21 UTC, kyeongraekim commented
LGTM!!